### PR TITLE
Fix onDOMLoad svgXHR call

### LINKED ISSUE #75: document.addEventListener must be passed a function, not function invokation
We keep running into a probem with svgXHR occasionally throwing the following error:

```
Uncaught TypeError: Cannot read property 'insertBefore' of null
```

And here's the [culprit](https://github.com/mrsum/webpack-svgstore-plugin/blob/develop/helpers/utils.js#L285):

```
document.addEventListener('DOMContentLoaded', svgXHR('hash', 'dir'), false);
```

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener):

> `target.addEventListener(type, listener[, useCapture]);`
> **listener**
> The object that receives a notification when an event of the specified type occurs. This must be an object implementing the EventListener interface, or **simply a JavaScript function**.

The code above should be: 

```
document.addEventListener('DOMContentLoaded', function() { svgXHR('hash', 'dir'); }, false);
```

### PR DESCRIPTION
**Pull request by dmitriid**
Fix #75

### CODE REVIEW

**Comment by KhramtsovMaksim** [comment]
Please add this changes asap.

**Comment by mrsum** [comment]
@dmitriid @KhramtsovMaksim try 3.0.0-alpha.2

**Comment by mrsum** [comment]
@dmitriid Hi. fixed. You can override your svgXHR function

**Comment by KhramtsovMaksim** [comment]
Thank you!

**Comment by dmitriid** [comment]
How and where can I override this function?

**Comment by mrsum** [comment]
@dmitriid put your function at your project and require that file.
for example

```javascript
var __svg__ = { path: './assets/svg/**/*.svg', name: 'assets/svg/[hash].logos.svg' };
var spriteLoad = function(options) {
 $.ajax(options.filename)
}
spriteLoad(__svg__);
```

**Comment by dmitriid** [comment]
Aha. So __svg__ is a magical variable (this is not immediately apparent from the docs). On would assume that it's the svgXHR that does that. You have to look into the code of the function itself to see that it's not the case and that a variable is silently being overwritten by the plugin.

I'm am extremely sceptical about such a decision, to say the least.

Is previous behaviour available in any form (where you could specify a chunk to prepend the function to and not depend on magical variables somewhere in code)?

**Comment by mrsum** [comment]
@dmitriid 
__svg__ – is the variable wich will modified inside webpack compile. 
That is better than last implementation, cause you can create a lot of other sprites with only one new SvgStore instance in webpack.config.js

Another case is opportunity of override svg ajax function, also AST compiler in webpack is much better than a lot of regexp and magic like in previous release. 
So, try to use it.

Best regards.

**Comment by dmitriid** [comment]
I will obviously try to use it. And ability to create multiple sprites is very nice.

However, magical variables that are silently overwritten? This is definitely obviously bad. `import` and `require` are known throughout JS world as:
- `require`: as an implementation detail for the most commonly used module system
- `import`: as part of the ES6 spec

Introducing not one, but several magical variables? That are silently overwritten? Erm... Nope.

**Comment by mrsum** [comment]
@dmitriid maybe, but a lot of plugins use same logic.
for example https://github.com/js-next/react-style-webpack-plugin/blob/master/lib/entry.js#L10

**Comment by dmitriid** [comment]
It looks like it creates a different temporary variable, not relying on a pre-existing magic variable.

**Pull request closed without merging**
