### PR TITLE
use webpack`s public path at runtime to resolve sprite url

### PR DESCRIPTION
**Pull request by ggarek**
fix issue #109

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
@mrsum @lgordey can you guys take a look please? We really need this

**Comment by mrsum** [comment]
@chicoxyzzy got it

**Comment by mrsum** [comment]
@ggarek @chicoxyzzy sorry for delay guys, can some one bump version into package.json to 3.0.5

**Comment by chicoxyzzy** [comment]
This change introduces breaking change as mentioned in #109. So it shouldn't be 3.0.5 if you follow SemVer 😃

**Comment by ggarek** [comment]
@mrsum moreover before applying the change some more work should be done, considering it is a breaking change. (i mean the `window.baseUrl magic`)

**Pull request merged**
